In [1]:
# Functions: Analyse the evoltion of average positive and negative
import numpy as np
import pandas as pd
import dask.dataframe as dd
from scipy import sparse
import time
from fun.fun import *

c:\Users\stirl\miniconda3\envs\network_env\Lib\site-packages\dask\dataframe\__init__.py:31: FutureWarning: 
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)


In [2]:
# -> IN : Read Edge List
edges_fn = "../data/edges.parquet"
print("reading edges ... ", end='')
start = time.time()
df = dd.read_parquet("../data/edges.parquet")
df[['source', 'target']] = df[['source', 'target']].astype('int32')
end = time.time()
print("read {:_} lines (took {:.1f}s)".format(len(df), (end-start)))
print(df.dtypes)
df.head()

reading edges ... read 684_732_453 lines (took 0.2s)
source    int32
target    int32
dtype: object


source  target
0      13  103151
1      13  214293
2  103151  214293
3      13  138731
4      13   42023

In [3]:
# extract unique nodes
nodes = dd.concat([df['source'], df['target']]).unique().compute()
num_nodes = len(nodes)
print("found {:_} unique nodes".format(num_nodes))

found 410_885 unique nodes


In [42]:
# 
n = 410_000
entries = int(n*n*0.004)
print("{:_}".format(entries))
row = np.random.randint(0, n-1, size=(entries), dtype='int32')
col = np.random.randint(0, n-1, size=(entries), dtype='int32')
data = np.ones_like(col)

672_400_000


In [43]:
# create csr matrix
mat = sparse.csr_matrix((data, (row, col)), shape=(n,n), dtype='int8')
show_n = 10
print(mat[0:show_n,0:35].toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [46]:
# save to npz
mat_fn = '../data/sparse_test.npz'
sparse.save_npz(mat_fn, mat)

In [45]:
# load from npz
#mat = sparse.load_npz(mat_fn)
#print(mat[0:20,0:35].toarray())
print(mat.toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [ ]:
# Create a mapping from node IDs to indices
node_to_index = {node: index for index, node in enumerate(nodes)}

# Function to process a partition of the DataFrame and build adjacency matrix
def build_adjacency_matrix(partition):
    adjacency = np.zeros((len(nodes), len(nodes)), dtype=np.uint8)
    for index, row in partition.iterrows():
        source_index = node_to_index[row['source']]
        target_index = node_to_index[row['target']]
        adjacency[source_index, target_index] = 1
        adjacency[target_index, source_index] = 1  # If graph is undirected
    return adjacency

# Build adjacency matrix in chunks
chunk_size = 10_000
adjacency_chunks = [
    sparse.csr_matrix(build_adjacency_matrix(partition))
    for partition in df.to_delayed()
]

# Concatenate chunks to get the final adjacency matrix
adjacency_matrix = sum(adjacency_chunks)

# Save adjacency matrix to a file
np.savez_compressed('adjacency_matrix.npz', data=adjacency_matrix.data, indices=adjacency_matrix.indices, indptr=adjacency_matrix.indptr, shape=adjacency_matrix.shape)


In [ ]:
# csr
data = np.ones(len(df), dtype='int8')
print(data)
row = df['source']
col = df['target']
adj_mat = csr_matrix((data, (row, col)), shape=(num_nodes, num_nodes))

In [10]:
s = 2
mat = np.zeros((s,s), dtype='int8')
print(mat)
print(type(mat[0,0]))

[[0 0]
 [0 0]]
<class 'numpy.int8'>


In [12]:
# 
adj_matrix = np.zeros((num_nodes, num_nodes), dtype='int8')
processed, total = 0, len(df)
for i, j in df.values:
    adj_matrix[i, j] = 1
    adj_matrix[j, i] = 1
    processed, _ = track_progress(total, processed, text='rows processed:', inc=50)
print("Done")

MemoryError: Unable to allocate 157. GiB for an array with shape (410885, 410885) and data type bool

In [3]:
# -> IN : Load tweets dataframe
tw = get_filtered_tweets_dataframe(dataset_fn)
print("Loaded {:_} tweets".format(len(tw)))
tw.head()

Importing dataset from tsv file ...

In [5]:
# -> IN : Read list of nodes
nodes = pd.read_csv('../data/node_ids.csv', index_col='twitter id')
print("Number of nodes: {:_}".format(len(nodes)))
nodes.head()


Number of nodes: 410_885


index
twitter id                
1200927495186505729      0
1200927503201816576      1
1200927507828097026      2
1200927511087067136      3
1200927514216062976      4

In [6]:
# Compute timestamp bins
increments = 100
ts_min, ts_max = min(tw['Timestamp']), max(tw['Timestamp'])
ts_inc = (ts_max - ts_min) / 100
ts_bins = [ ts_min + (i+1)*ts_inc for i in range(increments) ]

print("Min timestamp:", ts_min)
print("Max timestamp:", ts_max)
print("Timestamp increment:", ts_inc)

Min timestamp: 2019-12-01 00:00:01+00:00
Max timestamp: 2020-02-29 23:59:49+00:00
Timestamp increment: 0 days 21:50:23.880000


In [7]:
# Compute average cumulative sentiment for timestamp increments
ts = ts_min + 10*ts_inc
tweets = tw[tw['Timestamp'] < ts]
len(tweets)

47303